### ISSUE TITLE
Question about the network architecture in your work

### ISSUE THREAD

**Issue by Carco-git** [kage08/graph_sample_rl#1]
Hi, I found that you adopt DQN in your paper. But I also found some keywords like actor_critic in the code, is it means the method you used is a combination of DQN and actor-critic method?  Maybe, it seems like the DDPG method?

Thank you in advance.

**Comment by kage08** [comment]
I started off with DDPG and then used just the critic parts of the code for
DQN. Hence, the confusion in name. I'll try resolving that in the future.
:-)

Cheers

**Comment by Carco-git** [comment]
Thanks for your reply!
