### ISSUE TITLE
Steps to reproduce results in the paper

### ISSUE THREAD

**Issue by graphsudo** [kage08/graph_sample_rl#2]
Can you please provide the list of hyperparameters and other required steps to reproduce the results in the paper. I tried the default mentioned parameters as well as tried tuning the parameters and training multiple models but i can not get the values close to the one provided in the paper for twitter dataset. Also the models trained are not stable so wanted to check what I have been missing. 

Thanks!

**Comment by eryaaa** [comment]
hey，I have the same problem. Have you solved it?
